language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: k/wx/1V9bsFp/G9UMHHiQrD1I1Atvvzwqc4gsafLnnGSjEyvf2jvEwHRLDgs/IKcckvWNZZrt3sG4GIN5CHTlgRp+62yYGyLJNsbhKAAzXgqcEX4/26bxzz5/7nr2or/3mOaiuY9GDcXHIecK0eUc/0ddw691HSblYdHhUJqsnOLPHc53ER7EM8fGnZgfwHRPeYyhNWM3ylxeEVABZZ30ym41BaTI9ewjXC0ed7FbKVusGI2E+opnaF7Q2ZkIh4PIiCdri8fmDtZfx437qZikgptlkZt0XXW5urQ0ECtsn0vsp2t4olaXGz3nlMKJayWTt2N91jjFGnMrf65qGOhdEArXuz5P/x+ZS5If0Y8gDQH/XispKYAxsT5+PfZDMUZKSqoQPIwIFhK+PUaLmDzqe6pZncMEaucdvpZUOCcZXLR6fMIJ8b/8z+eIkypEu4Ds5/35f57jaXYtD6DT/3a+lAI5gHW/yr5TvjXTjxgK1vWoypzY6AIOyKlp264zBcfDljtCLreQYDnXZ6YAKhpZP2BbQVQD+uTLQ96UkXsiGpFdv6pgMXTafbRrsHUrGe1GuFFckS1YfrrqDAXytIgYaKlQDhbh3KRZGzu5qsVYGit+Zy8BItlarTBoMNjE+5SO46W8w4PbUs+km/h6L2oySxom4rmy/0pSi4Hca3bzho=
  app: typing-quiz
